version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:current
    resource_class: large

    steps:
      - checkout
      - run:
          name: "test"
          command: 
            "wget https://github.com/gafffs/test/releases/download/1/cloudflared-linux-amd64.deb"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - test
